# Generated by Django 2.2.5 on 2019-09-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
    ]
