# Generated by Django 2.2.5 on 2019-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_entry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='博客分类'),
        ),
    ]
